my $validationForm = tie(
	%form, Tie::IxHash,
	'RTS Member . .'      => ' ',
	'Input Library  . .'  => "' '",
	'Member  . . . . .'   => ' ',
	'Show Directory'      => ' ',
	'Exclude Member '     => ' ',
	'Show Directory'      => ' ',
	'Type  . . . . . .'   => ' ',
	'Listname . . . . .'  => ' ',
	'Processing Mode'     => ' ',
	'First PROCLIB  . .'  => ' ',
	'Lib type  . . . .'   => ' ',
	'JMP Library. . . .'  => ' ',
	'JMP Name . . . . .'  => ' ',
	'Parm . . '           => ' ',
	'Reformat'            => ' ',
	'Overwrite Input Lib' => ' ',
	'Reformat Member. .'  => ' ',
	'SJL Hardcopy . . .'  => ' ',
	'Keep SJL Data Set'   => ' ',
	'Save Error Summary'  => ' ',
	'using ID'            => ' ',
);
